CATALOGO_CRIMES = {
    "LATROCINIO": {"peso": 5.0},
    "EXTORSAO MEDIANTE SEQUESTRO": {"peso": 5.0},
    "ROUBO DE VEICULO": {"peso": 4.0},
    "ROUBO DE CARGA": {"peso": 4.0},
    "ROUBO A TRANSEUNTE": {"peso": 4.0},
    "FURTO DE VEICULO": {"peso": 3.0},
    "FURTO DE CARGA": {"peso": 3.0},
    "FURTO DE CELULAR": {"peso": 3.0},
    "DANO": {"peso": 2.0},
    "OUTROS": {"peso": 1.0}
}

PALAVRAS_CHAVE_PERFIL = {
    "Ciclista": ["BICI", "CICLO", "BICICLETA", "PEDALAR"],
    "Motociclista": ["MOTO", "MOTOCICLETA", "CAPACETE", "MOTOBOY"],
    "Motorista": ["VEICULO", "CARGA", "CARRO", "CAMINHAO", "AUTOMOVEL"],
    "Pedestre": ["TRANSEUNTE", "CELULAR", "PEDESTRE", "CALCADA", "PONTO DE ONIBUS"],
}

LIMITES_GEOGRAFICOS = {"lat": (-25.5, -19.5), "lon": (-53.5, -44.0)}

ESQUEMA_CANONICO = {
    "NUM_BO": "string", "DATA_OCORRENCIA_BO": "datetime", "HORA_OCORRENCIA_BO": "string",
    "LATITUDE": "float", "LONGITUDE": "float", "NATUREZA_APURADA": "string", 
    "DESCR_TIPOLOCAL": "string", "ANO_BASE": "int"
}

DICIONARIO_SEMANTICO = {
    "NUM_BO": ["NUM_BO", "NUMERO_BO", "BO_NUMERO", "N_BO"],
    "DATA_OCORRENCIA_BO": ["DATA_OCORRENCIA_BO", "DATA_FATO", "DATAOCORRENCIA", "DATA"],
    "HORA_OCORRENCIA_BO": ["HORA_OCORRENCIA_BO", "HORA_FATO", "HORAOCORRENCIA"],
    "LATITUDE": ["LATITUDE", "LAT", "LATITUDEDECIMAL", "LATITUDE_Y"],
    "LONGITUDE": ["LONGITUDE", "LON", "LONG", "LONGITUDEDECIMAL", "LONGITUDE_X"],
    "NATUREZA_APURADA": ["NATUREZA_APURADA", "NATUREZA", "TIPO_CRIME", "RUBRICA"],
    "DESCR_TIPOLOCAL": ["DESCR_TIPOLOCAL", "TIPOLOCAL", "LOCAL", "TIPO_LOCAL"]
}
COLUNAS_REFINED_EVENTOS = list(ESQUEMA_CANONICO.keys())
