
CATALOGO_CRIMES = {
    'FURTO DE VEICULO': {'perfil': 'MOTORISTA', 'peso': 1.0},
    'ROUBO DE VEICULO': {'perfil': 'MOTORISTA', 'peso': 2.5},
    'ROUBO DE CARGA': {'perfil': 'MOTORISTA', 'peso': 2.5},
    'FURTO DE CARGA': {'perfil': 'MOTORISTA', 'peso': 1.0},
    'LATROCINIO': {'perfil': 'TODOS', 'peso': 5.0},
    'EXTORSAO MEDIANTE SEQUESTRO': {'perfil': 'TODOS', 'peso': 5.0}
}


TIPOS_LOCAL_PERMITIDOS = [
    'VIA PUBLICA', 
    'RODOVIA/ESTRADA'
]


SUBTIPOS_LOCAL_PERMITIDOS = [
    'VIA PUBLICA', 'TRANSEUNTE', 'ACOSTAMENTO', 'AREA DE DESCANSO',
    'BALANCA', 'CICLOFAIXA', 'CICLOVIA', 'DE FRENTE A RESIDENCIA DA VITIMA',
    'FEIRA LIVRE', 'INTERIOR DE VEICULO DE CARGA', 'INTERIOR DE VEICULO DE PARTICULAR',
    'POSTO DE AUXILIO', 'POSTO DE FISCALIZACAO', 'POSTO POLICIAL',
    'PRACA', 'PRACA DE PEDAGIO', 'SEMAFORO', 'TUNEL/VIADUTO/PONTE',
    'VEICULO EM MOVIMENTO'
]

# Limites territoriais de integridade para o Estado de São Paulo
LIMITES_SP = {'lat': (-25.5, -19.5), 'lon': (-53.5, -44.0)}

# colunas textuais sujeitas à higienização e normalização
COLUNAS_TEXTO = [
    'NATUREZA_APURADA', 'NOME_MUNICIPIO', 
    'DESCR_TIPOLOCAL', 'DESCR_SUBTIPOLOCAL'
]


COLUNAS_REFINED = [
    'NUM_BO', 'DATA_OCORRENCIA_BO', 'HORA_OCORRENCIA_BO', 
    'LATITUDE', 'LONGITUDE', 'NATUREZA_APURADA', 
    'NOME_MUNICIPIO', 'DESCR_TIPOLOCAL', 'DESCR_SUBTIPOLOCAL', 'ANO_BASE'
]
