name: Discovery SafeDriver OSM
on:
  workflow_dispatch:

jobs:
  discovery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install GDAL Tools
        run: sudo apt-get update && sudo apt-get install -y gdal-bin

      - name: Download Real PBF
        run: |
          wget -L --user-agent="Mozilla/5.0" https://download.geofabrik.de/south-america/brazil/sudeste-latest.osm.pbf -O data.osm.pbf
          ls -lh data.osm.pbf

      - name: 🔍 Interrogando Camadas (Esquema Real)
        run: |
          echo "--- LISTANDO CAMADAS ---"
          ogrinfo data.osm.pbf
          
          echo "--- ESQUEMA DA CAMADA DE PONTOS ---"
          ogrinfo -so data.osm.pbf points
          
          echo "--- ESQUEMA DA CAMADA DE LINHAS (RUAS) ---"
          ogrinfo -so data.osm.pbf lines
