name: Teste de Eficiencia de Motores

on: [push, workflow_dispatch]

jobs:
  validacao:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Instalacao de pacotes
        run: pip install pandas numpy xgboost prophet pyarrow fastparquet scikit-learn
      - name: Execucao do script
        run: python valida_motores.py
      - name: Armazenar resultado
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-performance
          path: validacao_motores_2025.txt
