name: Teste de Eficiencia

on: [push, workflow_dispatch]

jobs:
  benchmarking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bibliotecas Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Instalar Dependencias
        run: pip install pandas numpy xgboost prophet pyarrow fastparquet scikit-learn
      - name: Run Benchmarking
        run: python valida_tcc.py
      - name: Download Relatorio
        uses: actions/upload-artifact@v4
        with:
          name: Relatorio-Final-TCC
          path: resultado_teste.txt
